[env]
OTEL_EXPORTER_OTLP_ENDPOINT = "http://localhost:5080/api/default"
## renovate: datasource=github-releases packageName=openobserve/openobserve versioning=semver automerge=true
OPENOBSERVE_VERSION = "v0.90.3"

# graft:keep-start
# Project-specific dependencies are listed here.

RUST_LOG = "warn,tepra_core=trace,tepra_api=trace,tepra_web=trace"
# graft:keep-end

[tools]
"aqua:ast-grep/ast-grep" = "0.43.0"
"aqua:cli/cli" = "2.95.0"
"aqua:EmbarkStudios/cargo-deny" = "0.19.9"
"aqua:taiki-e/cargo-llvm-cov" = "0.8.7"
"cargo:cargo-nextest" = "0.9.101"
"aqua:watchexec/cargo-watch" = "8.5.3"
"cargo:cargo-sweep" = "0.8.0"
"github:naa0yama/graft" = "0.5.9"
"github:rust-secure-code/cargo-auditable" = "0.7.5"
actionlint = "1.7.12"
dprint = "0.54.0"
ghalint = "1.5.6"
gitleaks = "8.30.1"
tmux = "3.6a"
usage = "3.5.2"
zizmor = "1.26.1"

[task_config]
includes = [".mise/tasks.toml", ".mise/overrides.toml"]
